networks:
  openfga:
  core:

services:
  database:
    image: mongodb/atlas
    container_name: database
    networks:
      - core
  bifrost:
    container_name: bifrost
    networks:
      - openfga
      - core
    build:
      context: .
      dockerfile: ./bifrost/Dockerfile
      target: development
    command: npm run start:debug
    env_file: ./.env.local
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - openfga
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    networks:
      - openfga
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    networks:
      - openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
      - OPENFGA_PLAYGROUND_ENABLED=false
    command: run
    ports:
      # Needed for the http server
      - '8080:8080'
      # Needed for the grpc server (if used)
      - '8081:8081'
      # Needed for the playground (Do not enable in prod!)
      #- '3000:3001'
