services:
  bifrost:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  database:
    image: mongodb/atlas